### ISSUE TITLE
رفع یک خطا در کنسول

### ISSUE THREAD

**Issue by zoghal** [NabiKAZ/Twitter-Follower-Count#1]
سلام نبی جان
این اسکریپت ایده باحالی داشت! 
منتهی یه باگ داشت که باعث تولید خطا  توی کنسول میشد و در کل کندی ایجاد میکرد(فیرفاکس)

> Uncaught DOMException: XMLHttpRequest.responseText getter: responseText is only available if responseType is '' or 'text'.

که لازمه این تغییر توش اعمال بشه:
```
        xhr.addEventListener('load', function() {
            // Parse the response text as JSON
            var responseJSON = null;
            if ((xhr.responseType === 'text' || xhr.responseType === '') && xhr.responseText) {
                responseJSON = JSON.parse(xhr.responseText);
            } else {
                return;
            }
          //  var responseJSON = JSON.parse(xhr.responseText);
```

**Comment by NabiKAZ** [comment]
ممنون از گزارشت. درست میگی.
البته راه‌حلی که نوشتی اشتباس. پیام خطا کلی میگه responseType میتونه '' یا 'text' باشه، اما دلیل نمیشه ادامه کد ما و JSON.parse بتونه پردازشش کنه.
مثلاً حتی وقتی یه فیلم نمایش داده میشه برگشتی m3u8 و تایپ تکست هست اما json parse روش خطا میده.
در هر صورت خطا رو با try/catch هندل کردم.
