### ISSUE TITLE
does not work on Arc browser

### ISSUE THREAD

**Issue by hadifarnoud** [NabiKAZ/Twitter-Follower-Count#3]
I did add the script as a "Boost" in Arc browser but does not seems to work

**Comment by NabiKAZ** [comment]
سلام،

به نظر میرسه آرک الان فقط برای مک موجوده و متأسفانه من الان مک ندارم که تست کنم.
اون بوست که گفتید ظاهراً یه چیزی مخصوص خودش.
اما برای اجرای این اسکریپت شما نیاز دارید ابتدا افزونه [TamperMonkey](https://www.tampermonkey.net/) رو نصب کنید. اغلب بروزرهای معروف رو پشتیبانی میکنه.
اما راجع آرک چیزی توی سایتش ننوشته و اگر مستقیم پشتیبانی نمیکرد. با توجه به اینکه هسته آرک از کرومیوم استفاده کرده، شاید بتونید فایل افزونه رو به شکل مستقیم نصب کنید. توی سایتش قسمت دانلود یه فایل CRX داره که اونو باید تست کنید. من اینجا هم میزارمش:
https://data.tampermonkey.net/tampermonkey_stable.crx
امتحانش کنید ببینید چی میشه.
این تازه افزونه TamperMonkey هست که اگر موفق شدید نصب کنید. بعدش دیگه اوکیه و تنها کافیه همین اسکریپت رو از گیت‌هاب بگیرید و توی اون افزونه واردش کنید.

**Comment by hadifarnoud** [comment]
مرسی از توضیحت. آرک قابلیت js ران کردن داره توی Boostهاش نمیدونم چرا کار نمیکنه. حالا از افزونه‌ای که دادی نصب میکنم

**Comment by NabiKAZ** [comment]
موضوع اینه اسکریپت به زبان js هست اما تفسیرش توسط افزونه TamperMonkey انجام میشه. یعنی یه جاوااسکریپت خاص هست که فرمان و دستوراتی بهش اضافه شده.
